#!/bin/sh

# Tonton Jo - 2022
# Join me on Youtube: https://www.youtube.com/c/tontonjo

# This script is used to show some informationals informations when login on system

# USAGE
## Download the motd file
# wget -qO /etc/update-motd.d/01-jo https://github.com/Tontonjo/debian/raw/master/etc/update-motd.d/01-jo
## make it executable
# chmod +x /etc/update-motd.d/01-jo
## make a backup and delete motd file
# cp /etc/motd /etc/motd.bck && rm -rf motd
## Delete uname motd script
# rm -rf /etc/update-motd.d/10-uname

# SOURCES:
# https://cloudybarz.com/custom-motd-in-linux-debian/
# https://unix.stackexchange.com/questions/267562/show-only-physical-disks-when-using-df-and-mount


# V1.0: Initial Release

freespace=$(df -H --type mount --type btrfs --type ext4 --type ext3 --type ext2 --type vfat --type iso9660)

echo
echo $(hostnamectl | grep -i Operating)
echo
echo " Welcome to: $(hostname)"
echo " User: user: $(id -u -n)"
echo " Host IP:    $(hostname -i)"
echo
echo
echo " CPU:      $(cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2)"
echo " Memory:    $(free -m | head -n 2 | tail -n 1 | awk {'print $2'}) M"
echo " Swap:      $(free -m | tail -n 1 | awk {'print $2'}) M"
echo
echo " Disk:      
 $(echo "$freespace")"
